user nginx;
worker_processes auto;
worker_rlimit_nofile 1024;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 10000;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Trust X-Forwarded-For header from ingress
    set_real_ip_from 0.0.0.0;
    real_ip_header    X-Forwarded-For;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information

    ## Flutter 
    server {
        listen 80 default_server; 
        root         /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    
    }
} 
